image: Visual Studio 2017


install:
  # Скачиваем rustup
  - appveyor DownloadFile https://sourceforge.net/projects/mingw/files/ -FileName mingw-get-setup.exe
  - mingw-get-setup -yv --default-toolchain msvc14 --default-host x86_64-pc-windows-msvc

init:
    - git config --global core.autocrlf input

shallow_clone: true              

matrix:
    fast_finish: false           

platform:
    - x86
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15
    
build_script:
    # скрипт сборки проекта:
    - mkdir build
    - cd build
    - cmake .. 
    - cmake --build . 

deploy:
    # выкладываем tagged-коммиты на GitHub Releases:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: <encrypted-github-token>

    artifact: package_name
    force_update: true

    on:
        appveyor_repo_tag: true
