

version: 1.0.{build}

image: Visual Studio 2015

configuration: Debug, Release

platform: Any CPU

environment:
    matrix:
        - TOOLCHAIN: msvc14
        - TOOLCHAIN: msvc15

build:

  parallel: true

  verbosity: minimal

